### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by muzihuole** [fsept11/FoolHD#1]
Hello，Thanks for your code first.
     I try to run this code  to generate FoolHD adversarial audio files. But when I run "python main.py -task targeted",  a type error occurs. that's it :
`Traceback (most recent call last):
  File "main.py", line 87, in <module>
    main()
  File "main.py", line 81, in main
    train_gae_targeted(gae_model, adv_model, dataset, gae_optimizer, opt.start, opt.end, **params)
  File "/home/FoolHD/code/utils/nn_gae_targeted.py", line 72, in train_gae
    dataset['train'].trim_dataset(start,end)
  File "/home/FoolHD/code/utils/datasets.py", line 79, in __getitem__
    fileid = self._walker[n]
TypeError: list indices must be integers or slices, not str` 
    Meanwhile, I don't understand what's mean of the train in 'dataset['train']'.
    Hope to get your help ！Thank you！

**Comment by fsepteixeira** [comment]
Hi,

dataset['train'] was a leftover a different version of the code that used a dataset that had partitions. It is actually a bug here.
Thank you for pointing it out, I've changed the portions of the code that use it. Let me know if it fixed your issue!

**Comment by muzihuole** [comment]
Thank you very much for your reply！

I try to run `python main.py -task targeted` again, and I find two bugs this time. 
Here are two errors and my solution:
1.
`File "/home/FoolHD/code/utils/nn_gae_targeted.py", line 77, in train_gae
    batch_size=batch_size, 
NameError: name 'batch_size' is not defined`
I change the code as that `batch_size=1`,  and it can run.
2.
 `Traceback (most recent call last):
  File "main.py", line 87, in <module>
    main()
  File "main.py", line 81, in main
    train_gae_targeted(gae_model, adv_model, dataset, gae_optimizer, opt.start, opt.end, **params)
  File "/home/FoolHD/code/utils/nn_gae_targeted.py", line 97, in train_gae
    f_log_all, f_name_all   = createLogFiles('logs/'+log_file+'all_{}to{}.log'.format(idxBeg,idxEnd if idxEnd>=0 else n_iterations))
  File "/home/FoolHD/code/utils/nn_gae_targeted.py", line 30, in createLogFiles
    f_file = open(f_name,"w")
FileNotFoundError: [Errno 2] No such file or directory: './log_logs/log_untargeted_all_0to2499.log.txt'`
 In "FoolHD/code/utils/nn_gae_targeted.py, line 29, in createLogFiles", I find the code `f_name = './log_{}.txt'.format(log_name)`. I change this code to `f_name = '{}'.format(log_name)`, and this can run.
That's all,  I have fixed my issues. Thanks for your attention!

**Comment by fsepteixeira** [comment]
Thank you for sharing these issues, the latest commit should fix them as well. 
If you have any further issues, feel free to let me know.
