### ISSUE TITLE
Could you please provide the code of two baseline attacks? 

### ISSUE THREAD

**Issue by muzihuole** [fsept11/FoolHD#2]
Dear author，
    I am so sorry to disturb you. As you can see, I am a novice at adversarial examples. I did not find the code of FGSM and BIM attacks in your code. If you can upload the code of two baseline attacks： FGSM and BIM，it will help me a lot. Look forward to your reply.
    Thank you!

**Comment by fsepteixeira** [comment]
Yes, but it might take a few days. I'll do it as soon as I find the time!

**Comment by muzihuole** [comment]
Thank you very much for your reply. Looking forward to your very helpful code！

**Comment by muzihuole** [comment]
Merry Christmas！Can you provide the code of training speaker identification model? Maybe I can try to generate adversarial examples by myself.

**Comment by muzihuole** [comment]
Hello, it's been a week. When will you be able to upload the code? Is this okay this week? Thank you.

**Comment by Ian-Tam** [comment]
Hello, thanks for your code! Would you like to tell me what the loss function you use for training the Audionet, it will be great helpful for me~

**Comment by fsepteixeira** [comment]
> Hello, it's been a week. When will you be able to upload the code? Is this okay this week? Thank you.

Hi.

I've not had the time to properly clean up the code yet, but you can find the necessary functions in utils/nn_fgsm.py, which I've just uploaded.

You will need to install this toolbox:
https://adversarial-robustness-toolbox.readthedocs.io/en/latest/

To call the functions simply add an option in the main.py file. When I have the time I will update the main function in this repository to have this option. 

In the meantime let me know if you have any issues with the code.

**Comment by fsepteixeira** [comment]
> Hello, thanks for your code! Would you like to tell me what the loss function you use for training the Audionet, it will be great helpful for me~

Hi!
Can I ask you what you mean by the Audionet?

**Comment by muzihuole** [comment]
Thanks for your reply. I will try to use it.
